language: objective-c
osx_image: xcode7
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -project ISHHoverBar.xcodeproj -scheme ISHHoverBar -destination 'platform=iOS Simulator,name=iPhone 6' clean build | xcpretty
  - xcodebuild -project ISHHoverBar.xcodeproj -scheme ISHHoverBar -destination 'platform=iOS Simulator,name=iPhone 6' clean test | xcpretty
